"""
Comprehensive disposable and temporary email domain detector.
Maintains a curated, high-performance O(1) set of known disposable email providers.
"""

from typing import Set

DISPOSABLE_DOMAINS: Set[str] = {
    # Popular disposable webmail services
    "10minutemail.com",
    "10minutemail.net",
    "10minutemail.co.uk",
    "10minutemail.de",
    "20minutemail.com",
    "airmail.news",
    "anonaddy.com",
    "antichef.com",
    "armyspy.com",
    "binkmail.com",
    "bobmail.info",
    "burnermail.io",
    "byom.de",
    "chacuo.net",
    "cool.fr.nf",
    "courriel.fr.nf",
    "crazymailing.com",
    "cuvox.de",
    "dayrep.com",
    "deadaddress.com",
    "discard.email",
    "discardmail.com",
    "discardmail.de",
    "disposable.com",
    "disposablemail.com",
    "dispostable.com",
    "dodgit.com",
    "drdrb.net",
    "dropmail.me",
    "einrot.com",
    "emailondeck.com",
    "emailtemporanea.net",
    "emailtemporaire.fr",
    "emltmp.com",
    "evopoint.net",
    "fakemailgenerator.com",
    "fleckens.hu",
    "fmail.cf",
    "fmail.ga",
    "fmail.gq",
    "fmail.ml",
    "generator.email",
    "getairmail.com",
    "getnada.com",
    "ghostlymail.com",
    "gishpuppy.com",
    "goemailgo.com",
    "grr.la",
    "guerillamail.biz",
    "guerillamail.com",
    "guerillamail.de",
    "guerillamail.net",
    "guerillamail.org",
    "guerrillamail.biz",
    "guerrillamail.com",
    "guerrillamail.de",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamailblock.com",
    "gustr.com",
    "harakirimail.com",
    "hushmail.me",
    "inboxbear.com",
    "inboxkitten.com",
    "incognitomail.org",
    "instantemailaddress.com",
    "instantmail.im",
    "jourrapide.com",
    "kasmail.com",
    "koszmail.pl",
    "laste.ml",
    "linshiyouxiang.net",
    "maildrop.cc",
    "mailcatch.com",
    "mail-temporaire.fr",
    "mailnull.com",
    "mailhazard.com",
    "mailhazard.us",
    "mailnesia.com",
    "mailscrap.com",
    "mailtemp.net",
    "mailimate.com",
    "mailin8r.com",
    "mailinator.com",
    "mailinator.net",
    "mailinator2.com",
    "mailinator.org",
    "meltmail.com",
    "mintemail.com",
    "mohmal.com",
    "mohmal.im",
    "mohmal.in",
    "mytrashmail.com",
    "mytemp.email",
    "nada.ltd",
    "nonspam.eu",
    "no-spam.ws",
    "nospam4.us",
    "nowmymail.com",
    "oneoffmail.com",
    "owlpic.com",
    "pookmail.com",
    "pokemail.net",
    "postinbox.com",
    "privacymail.com",
    "quickinbox.com",
    "rcpt.at",
    "rhyta.com",
    "safetymail.info",
    "sharklasers.com",
    "shitmail.me",
    "shitmail.org",
    "shortmail.net",
    "slopsbox.com",
    "sogetthis.com",
    "soodonims.com",
    "spam4.me",
    "spambob.com",
    "spambog.com",
    "spambox.us",
    "spamcannon.com",
    "spamcon.org",
    "spamday.com",
    "spamex.com",
    "spamfree24.org",
    "spamgourmet.com",
    "spamhole.com",
    "spaml.de",
    "spamspot.com",
    "superrito.com",
    "suremail.info",
    "teleworm.us",
    "tempail.com",
    "tempinbox.com",
    "tempmail.com",
    "temp-mail.org",
    "temp-mail.ru",
    "tempmail.net",
    "tempmailaddress.com",
    "tempmailer.com",
    "tempmailer.net",
    "tempmailo.com",
    "temporarymail.com",
    "throwawayemailaddress.com",
    "throwawaymail.com",
    "trashmail.at",
    "trashmail.com",
    "trashmail.de",
    "trashmail.io",
    "trashmail.me",
    "trashmail.net",
    "trashmail.org",
    "trashymail.com",
    "twinmail.de",
    "uggsrock.com",
    "vpn.st",
    "wegwerfadresse.de",
    "wegwerfemail.de",
    "wegwerfmail.de",
    "wegwerfmail.net",
    "wegwerfmail.org",
    "whyspam.me",
    "yopmail.com",
    "yopmail.fr",
    "yopmail.net",
    "zippymail.info",
    "zoemail.org",
}


def is_disposable_email(email_or_domain: str | None) -> bool:
    """
    Checks whether an email address or domain name belongs to a known disposable
    or temporary email provider.
    """
    if not email_or_domain or not isinstance(email_or_domain, str):
        return False

    target = email_or_domain.lower().strip()
    if "@" in target:
        target = target.split("@")[-1]

    target = target.removeprefix("www.")
    return target in DISPOSABLE_DOMAINS
